example:
  property: DEV EXAMPLE
spring:
  datasource:
    url: jdbc:postgresql://my-postgres:5432/ms_prac
    username: postgres
    password: postgres
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql